<a href="https://colab.research.google.com/github/simonme42/ANN_experiments/blob/master/Calculator_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.preprocessing import MinMaxScaler

In [0]:
# create the training data depending on what to learn and what the max number is
def create_target_data(learn="+", range=20):
  if learn == "+":
    X_unscaled = np.random.randint(range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]+X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]+X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "-":
    X_unscaled = np.random.randint(range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]-X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]-X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "*":
    X_unscaled = np.random.randint(20, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]*X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]*X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "/":
    X_unscaled = np.random.randint(1,range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]/X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(1,range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]/X_test_unscaled[:,1]).reshape(-1, 1)
  return X_test_unscaled, Y_test_unscaled, X_unscaled, Y_unscaled

In [3]:
(X_test_unscaled, Y_test_unscaled,
    X_unscaled, Y_unscaled) = create_target_data(learn="/", range = 20)

print(X_unscaled[0:10])
print(Y_unscaled[0:10])

[[ 9 17]
 [14 15]
 [ 1 18]
 [19 16]
 [ 4  4]
 [ 8 10]
 [12 19]
 [ 7 17]
 [10 10]
 [ 7 16]]
[[0.52941176]
 [0.93333333]
 [0.05555556]
 [1.1875    ]
 [1.        ]
 [0.8       ]
 [0.63157895]
 [0.41176471]
 [1.        ]
 [0.4375    ]]


In [4]:
# scale the training data
X_scaler = MinMaxScaler()
Y_scaler = MinMaxScaler()

X = X_scaler.fit_transform(X_unscaled)
Y = Y_scaler.fit_transform(Y_unscaled)

print(X.shape)
print(Y.shape)
print(X[0:10])
print(Y[0:10])

(10000, 2)
(10000, 1)
[[0.44444444 0.88888889]
 [0.72222222 0.77777778]
 [0.         0.94444444]
 [1.         0.83333333]
 [0.16666667 0.16666667]
 [0.38888889 0.5       ]
 [0.61111111 1.        ]
 [0.33333333 0.88888889]
 [0.5        0.5       ]
 [0.33333333 0.83333333]]
[[0.0251634 ]
 [0.04648148]
 [0.00015432]
 [0.05989583]
 [0.05      ]
 [0.03944444]
 [0.03055556]
 [0.01895425]
 [0.05      ]
 [0.0203125 ]]


In [0]:
# set up ann model
calc_model = tf.keras.Sequential()
calc_model.add(layers.Dense(64, activation='relu'))
#calc_model.add(layers.Dense(64, activation='relu'))
calc_model.add(layers.Dense(1))

calc_model.compile(optimizer="adam",
              loss='mean_squared_error',
              metrics=['mse'])

In [6]:
# train ann model
calc_model.fit(X,Y, epochs=50)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Train on 10000 samples
Epoch 1/50
10000/10000 [==============================] - 1s 105us/sample - loss: 0.0082 - mean_squared_error: 0.0082
Epoch 2/50
10000/10000 [==============================] - 1s 65us/sample - loss: 0.0033 - mean_squared_error: 0.0033
Epoch 3/50
10000/10000 [==============================] - 1s 64us/sample - loss: 0.0019 - mean_squared_error: 0.0019
Epoch 4/50
10000/10000 [==============================] - 1s 65us/sample - loss: 0.0012 - mean_squared_error: 0.0012
Epoch 5/50
10000/10000 [==============================] - 1s 64us/sample - loss: 7.7320e-04 - mean_squared_error: 7.7320e-04
Epoch 6/50
10000/10000 [==============================] - 1s 64us/sample - loss: 5.0640e-04 - mean_squared_error: 5.0640e-04
Epoch 7/50
10000/10000 [==============================] - 1s 69us/sample - loss: 3.3725e-04 - mean_squared_error: 3.3725e-04
Epoch 8/50
10000/10000 [============================

In [7]:
# scale test data and validate trained neural net
X_test = X_scaler.transform(X_test_unscaled)

Y_pred = calc_model.predict(X_test)
Y_pred_rescaled = Y_scaler.inverse_transform(Y_pred)

print(Y_test_unscaled[0:10])
print(Y_pred_rescaled[0:10])

[[2.66666667]
 [1.42857143]
 [3.        ]
 [3.        ]
 [0.2       ]
 [1.05882353]
 [0.16666667]
 [0.72727273]
 [1.        ]
 [2.375     ]]
[[2.6734114 ]
 [1.4292985 ]
 [2.9915745 ]
 [3.0125806 ]
 [0.17101863]
 [1.013732  ]
 [0.14443272]
 [0.71834105]
 [0.9721589 ]
 [2.337902  ]]


In [8]:
# compute the prediction error
error = Y_pred_rescaled - Y_test_unscaled
squared_error = error*error

print(error[0:10])
print(f"mean error: {np.mean(error)}")
print(f"mean squared error: {np.mean(squared_error)}")

[[ 0.0067447 ]
 [ 0.00072709]
 [-0.00842547]
 [ 0.01258063]
 [-0.02898137]
 [-0.04509157]
 [-0.02223394]
 [-0.00893167]
 [-0.02784109]
 [-0.03709793]]
mean error: -0.013494786534755098
mean squared error: 0.0007116792672492842
