<a href="https://colab.research.google.com/github/simonme42/ANN_experiments/blob/master/Calculator_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.preprocessing import MinMaxScaler

In [0]:
def create_target_data(learn="+"):
  if learn == "+":
    X_unscaled = np.random.randint(20, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]+X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(20, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]+X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "-":
    X_unscaled = np.random.randint(20, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]-X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(20, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]-X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "*":
    X_unscaled = np.random.randint(20, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]*X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(20, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]*X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "/":
    X_unscaled = np.random.randint(1,20, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]/X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(1,20, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]/X_test_unscaled[:,1]).reshape(-1, 1)
  return X_test_unscaled, Y_test_unscaled, X_unscaled, Y_unscaled

In [62]:
(X_test_unscaled, Y_test_unscaled,
    X_unscaled, Y_unscaled) = create_target_data(learn="/")

print(X_unscaled[0:10])
print(Y_unscaled[0:10])

[[13  7]
 [18 18]
 [13 14]
 [ 4 18]
 [ 1 16]
 [ 3 17]
 [13 13]
 [ 6 15]
 [12  2]
 [ 8  3]]
[[1.85714286]
 [1.        ]
 [0.92857143]
 [0.22222222]
 [0.0625    ]
 [0.17647059]
 [1.        ]
 [0.4       ]
 [6.        ]
 [2.66666667]]


In [63]:
X_scaler = MinMaxScaler()
Y_scaler = MinMaxScaler()

X = X_scaler.fit_transform(X_unscaled)
Y = Y_scaler.fit_transform(Y_unscaled)

print(X.shape)
print(Y.shape)
print(X[0:10])
print(Y[0:10])

(10000, 2)
(10000, 1)
[[0.66666667 0.33333333]
 [0.94444444 0.94444444]
 [0.66666667 0.72222222]
 [0.16666667 0.94444444]
 [0.         0.83333333]
 [0.11111111 0.88888889]
 [0.66666667 0.66666667]
 [0.27777778 0.77777778]
 [0.61111111 0.05555556]
 [0.38888889 0.11111111]]
[[0.0952381 ]
 [0.05      ]
 [0.04623016]
 [0.00895062]
 [0.00052083]
 [0.00653595]
 [0.05      ]
 [0.01833333]
 [0.31388889]
 [0.13796296]]


In [0]:
calc_model = tf.keras.Sequential()
calc_model.add(layers.Dense(64, activation='relu'))
#calc_model.add(layers.Dense(64, activation='relu'))
calc_model.add(layers.Dense(1))

calc_model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='mean_squared_error',
              metrics=['mse'])

In [69]:
calc_model.fit(X,Y, epochs=50)

Train on 10000 samples
Epoch 1/50
10000/10000 [==============================] - 1s 79us/sample - loss: 0.0078 - mean_squared_error: 0.0078
Epoch 2/50
10000/10000 [==============================] - 1s 68us/sample - loss: 0.0027 - mean_squared_error: 0.0027
Epoch 3/50
10000/10000 [==============================] - 1s 69us/sample - loss: 0.0016 - mean_squared_error: 0.0016
Epoch 4/50
10000/10000 [==============================] - 1s 68us/sample - loss: 0.0010 - mean_squared_error: 0.0010
Epoch 5/50
10000/10000 [==============================] - 1s 71us/sample - loss: 6.4560e-04 - mean_squared_error: 6.4560e-04
Epoch 6/50
10000/10000 [==============================] - 1s 71us/sample - loss: 4.4513e-04 - mean_squared_error: 4.4513e-04
Epoch 7/50
10000/10000 [==============================] - 1s 70us/sample - loss: 2.9160e-04 - mean_squared_error: 2.9160e-04
Epoch 8/50
10000/10000 [==============================] - 1s 65us/sample - loss: 1.9855e-04 - mean_squared_error: 1.9855e-04
Epoch 9/5

In [70]:
X_test = X_scaler.transform(X_test_unscaled)

Y_pred = calc_model.predict(X_test)
Y_pred_rescaled = Y_scaler.inverse_transform(Y_pred)

print(Y_test_unscaled[0:10])
print(Y_pred_rescaled[0:10])

[[1.66666667]
 [1.14285714]
 [0.75      ]
 [0.25      ]
 [0.11764706]
 [5.33333333]
 [0.63636364]
 [0.4       ]
 [8.5       ]
 [3.        ]]
[[1.6719533 ]
 [1.1373466 ]
 [0.7594288 ]
 [0.26820865]
 [0.11384234]
 [5.332091  ]
 [0.6471986 ]
 [0.4183327 ]
 [8.461978  ]
 [3.020291  ]]


In [71]:
error = Y_pred_rescaled - Y_test_unscaled

error[0:10]

array([[ 0.00528665],
       [-0.00551052],
       [ 0.0094288 ],
       [ 0.01820865],
       [-0.00380472],
       [-0.00124248],
       [ 0.01083498],
       [ 0.0183327 ],
       [-0.03802204],
       [ 0.02029109]])