<a href="https://colab.research.google.com/github/simonme42/ANN_experiments/blob/master/Calculator_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.preprocessing import MinMaxScaler

In [0]:
# create the training data depending on what to learn and what the max number is
def create_target_data(learn="+", range=20):
  if learn == "+":
    X_unscaled = np.random.randint(range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]+X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]+X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "-":
    X_unscaled = np.random.randint(range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]-X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]-X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "*":
    X_unscaled = np.random.randint(20, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]*X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]*X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "/":
    X_unscaled = np.random.randint(1,range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]/X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(1,range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]/X_test_unscaled[:,1]).reshape(-1, 1)
  return X_test_unscaled, Y_test_unscaled, X_unscaled, Y_unscaled

In [75]:
(X_test_unscaled, Y_test_unscaled,
    X_unscaled, Y_unscaled) = create_target_data(learn="/", range = 40)

print(X_unscaled[0:10])
print(Y_unscaled[0:10])

[[25 34]
 [19 15]
 [10 19]
 [ 5 16]
 [ 9 27]
 [29 19]
 [ 6 15]
 [34 25]
 [24 19]
 [38 25]]
[[0.73529412]
 [1.26666667]
 [0.52631579]
 [0.3125    ]
 [0.33333333]
 [1.52631579]
 [0.4       ]
 [1.36      ]
 [1.26315789]
 [1.52      ]]


In [76]:
# scale the training data
X_scaler = MinMaxScaler()
Y_scaler = MinMaxScaler()

X = X_scaler.fit_transform(X_unscaled)
Y = Y_scaler.fit_transform(Y_unscaled)

print(X.shape)
print(Y.shape)
print(X[0:10])
print(Y[0:10])

(10000, 2)
(10000, 1)
[[0.63157895 0.86842105]
 [0.47368421 0.36842105]
 [0.23684211 0.47368421]
 [0.10526316 0.39473684]
 [0.21052632 0.68421053]
 [0.73684211 0.47368421]
 [0.13157895 0.36842105]
 [0.86842105 0.63157895]
 [0.60526316 0.47368421]
 [0.97368421 0.63157895]]
[[0.0182082 ]
 [0.03184211]
 [0.01284626]
 [0.0073602 ]
 [0.00789474]
 [0.03850416]
 [0.00960526]
 [0.03423684]
 [0.03175208]
 [0.03834211]]


In [0]:
# set up ann model
calc_model = tf.keras.Sequential()
calc_model.add(layers.Dense(64, activation='relu'))
#calc_model.add(layers.Dense(64, activation='relu'))
calc_model.add(layers.Dense(1))

calc_model.compile(optimizer="adam",
              loss='mean_squared_error',
              metrics=['mse'])

In [78]:
# train ann model
calc_model.fit(X,Y, epochs=50)

Train on 10000 samples
Epoch 1/50
10000/10000 [==============================] - 1s 76us/sample - loss: 0.0107 - mean_squared_error: 0.0107
Epoch 2/50
10000/10000 [==============================] - 1s 68us/sample - loss: 0.0047 - mean_squared_error: 0.0047
Epoch 3/50
10000/10000 [==============================] - 1s 69us/sample - loss: 0.0036 - mean_squared_error: 0.0036
Epoch 4/50
10000/10000 [==============================] - 1s 68us/sample - loss: 0.0029 - mean_squared_error: 0.0029
Epoch 5/50
10000/10000 [==============================] - 1s 72us/sample - loss: 0.0024 - mean_squared_error: 0.0024
Epoch 6/50
10000/10000 [==============================] - 1s 65us/sample - loss: 0.0019 - mean_squared_error: 0.0019
Epoch 7/50
10000/10000 [==============================] - 1s 68us/sample - loss: 0.0016 - mean_squared_error: 0.0016
Epoch 8/50
10000/10000 [==============================] - 1s 68us/sample - loss: 0.0014 - mean_squared_error: 0.0014
Epoch 9/50
10000/10000 [=================

In [70]:
# scale test data and validate trained neural net
X_test = X_scaler.transform(X_test_unscaled)

Y_pred = calc_model.predict(X_test)
Y_pred_rescaled = Y_scaler.inverse_transform(Y_pred)

print(Y_test_unscaled[0:10])
print(Y_pred_rescaled[0:10])

[[1.66666667]
 [1.14285714]
 [0.75      ]
 [0.25      ]
 [0.11764706]
 [5.33333333]
 [0.63636364]
 [0.4       ]
 [8.5       ]
 [3.        ]]
[[1.6719533 ]
 [1.1373466 ]
 [0.7594288 ]
 [0.26820865]
 [0.11384234]
 [5.332091  ]
 [0.6471986 ]
 [0.4183327 ]
 [8.461978  ]
 [3.020291  ]]


In [71]:
# compute the prediction error
error = Y_pred_rescaled - Y_test_unscaled

error[0:10]

array([[ 0.00528665],
       [-0.00551052],
       [ 0.0094288 ],
       [ 0.01820865],
       [-0.00380472],
       [-0.00124248],
       [ 0.01083498],
       [ 0.0183327 ],
       [-0.03802204],
       [ 0.02029109]])