<a href="https://colab.research.google.com/github/simonme42/ANN_experiments/blob/master/Calculator_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.preprocessing import MinMaxScaler

In [0]:
# create the training data depending on what to learn and what the max number is
def create_target_data(learn="+", range=20):
  if learn == "+":
    X_unscaled = np.random.randint(range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]+X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]+X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "-":
    X_unscaled = np.random.randint(range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]-X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]-X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "*":
    X_unscaled = np.random.randint(20, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]*X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]*X_test_unscaled[:,1]).reshape(-1, 1)
  elif learn == "/":
    X_unscaled = np.random.randint(1,range, size=(10000, 2))
    Y_unscaled = (X_unscaled[:,0]/X_unscaled[:,1]).reshape(-1, 1)
    X_test_unscaled = np.random.randint(1,range, size=(1000, 2))
    Y_test_unscaled = (X_test_unscaled[:,0]/X_test_unscaled[:,1]).reshape(-1, 1)
  return X_test_unscaled, Y_test_unscaled, X_unscaled, Y_unscaled

In [79]:
(X_test_unscaled, Y_test_unscaled,
    X_unscaled, Y_unscaled) = create_target_data(learn="/", range = 20)

print(X_unscaled[0:10])
print(Y_unscaled[0:10])

[[11  7]
 [14  8]
 [ 4 15]
 [ 2  3]
 [17 11]
 [16  1]
 [ 3  5]
 [ 4  6]
 [14 13]
 [17  5]]
[[ 1.57142857]
 [ 1.75      ]
 [ 0.26666667]
 [ 0.66666667]
 [ 1.54545455]
 [16.        ]
 [ 0.6       ]
 [ 0.66666667]
 [ 1.07692308]
 [ 3.4       ]]


In [80]:
# scale the training data
X_scaler = MinMaxScaler()
Y_scaler = MinMaxScaler()

X = X_scaler.fit_transform(X_unscaled)
Y = Y_scaler.fit_transform(Y_unscaled)

print(X.shape)
print(Y.shape)
print(X[0:10])
print(Y[0:10])

(10000, 2)
(10000, 1)
[[0.55555556 0.33333333]
 [0.72222222 0.38888889]
 [0.16666667 0.77777778]
 [0.05555556 0.11111111]
 [0.88888889 0.55555556]
 [0.83333333 0.        ]
 [0.11111111 0.22222222]
 [0.16666667 0.27777778]
 [0.72222222 0.66666667]
 [0.88888889 0.22222222]]
[[0.08015873]
 [0.08958333]
 [0.0112963 ]
 [0.03240741]
 [0.07878788]
 [0.84166667]
 [0.02888889]
 [0.03240741]
 [0.05405983]
 [0.17666667]]


In [0]:
# set up ann model
calc_model = tf.keras.Sequential()
calc_model.add(layers.Dense(64, activation='relu'))
#calc_model.add(layers.Dense(64, activation='relu'))
calc_model.add(layers.Dense(1))

calc_model.compile(optimizer="adam",
              loss='mean_squared_error',
              metrics=['mse'])

In [82]:
# train ann model
calc_model.fit(X,Y, epochs=50)

Train on 10000 samples
Epoch 1/50
10000/10000 [==============================] - 1s 71us/sample - loss: 0.0087 - mean_squared_error: 0.0087
Epoch 2/50
10000/10000 [==============================] - 1s 68us/sample - loss: 0.0034 - mean_squared_error: 0.0034
Epoch 3/50
10000/10000 [==============================] - 1s 67us/sample - loss: 0.0020 - mean_squared_error: 0.0020
Epoch 4/50
10000/10000 [==============================] - 1s 69us/sample - loss: 0.0012 - mean_squared_error: 0.0012
Epoch 5/50
10000/10000 [==============================] - 1s 68us/sample - loss: 8.2051e-04 - mean_squared_error: 8.2051e-04
Epoch 6/50
10000/10000 [==============================] - 1s 68us/sample - loss: 5.5255e-04 - mean_squared_error: 5.5255e-04
Epoch 7/50
10000/10000 [==============================] - 1s 69us/sample - loss: 3.7385e-04 - mean_squared_error: 3.7385e-04
Epoch 8/50
10000/10000 [==============================] - 1s 68us/sample - loss: 2.6098e-04 - mean_squared_error: 2.6098e-04
Epoch 9/5

In [83]:
# scale test data and validate trained neural net
X_test = X_scaler.transform(X_test_unscaled)

Y_pred = calc_model.predict(X_test)
Y_pred_rescaled = Y_scaler.inverse_transform(Y_pred)

print(Y_test_unscaled[0:10])
print(Y_pred_rescaled[0:10])

[[0.35294118]
 [0.38888889]
 [0.85714286]
 [4.75      ]
 [1.28571429]
 [0.63157895]
 [2.        ]
 [1.54545455]
 [1.14285714]
 [0.72222222]]
[[0.28950047]
 [0.32350442]
 [0.79770046]
 [4.740251  ]
 [1.2195588 ]
 [0.56882745]
 [1.935845  ]
 [1.4705604 ]
 [1.0743746 ]
 [0.662982  ]]


In [84]:
# compute the prediction error
error = Y_pred_rescaled - Y_test_unscaled

error[0:10]

array([[-0.0634407 ],
       [-0.06538447],
       [-0.05944239],
       [-0.00974894],
       [-0.06615545],
       [-0.0627515 ],
       [-0.06415498],
       [-0.07489411],
       [-0.06848259],
       [-0.05924024]])